### ISSUE TITLE
Two way sync

### ISSUE THREAD

**Issue by miketaster** [jjssoftware/asustor-dropbox#2]
1.   So I have some test results but I am having trouble getting the script restarted.  I killed all python processes, deleted the lock file and still was getting the error that the script was busy.   I had to uninstall / reinstall so there is still a step I'm missing.

2.   Breaking up the large picture folders worked as I expected it to.  Dropbox itself has a little trouble with folders with close to 10000 files so breaking it up resolved that problem.  I needed to do that anyway.

New files are able to be added to the NAS from DropBox.

New files are able to be added to Dropbox from the NAS.

The only problem is that there is no file clean up.  This is the part that makes me nervous because all i can think of is deleting my data accidentally.  I will do a complete back up before I start any testing.

Example 1:  

- Action: Move a file from one folder to another using another device or on Dropbox's web interface

- Effect: The file gets copied over to the new folder.  The original file location is deleted on device X.  Dropbox syncs the file to the NAS  to the new location but the original file remains in the old location.  The file in the old location resyncs back to dropbox and back to device X.

Example 2:

- Action: Move a file from one folder to another within the Dropbox folder in the NAS

- Effect: The file gets copied over to the new folder.  The original file location is deleted on the NAS.  NAS  syncs the file to the to the new location in Dropbox but the original file remains in the old location in Dropbox and on Device X.  The file in the old (original) location resyncs back to the NAS.

**Comment by bebo-dot-dev** [comment]
I can tell you that the behavior you've described in your use case examples 1 + 2 is how the python updown.py script that gets executed in this app works right now. 

It's also worth pointing out that this behavior demonstrates this app will not intentionally remove files from either the NAS or dropbox right now; it actually can't because there's no code in the updown.py script like os.remove / os.removedirs / os.rename etc to remove files or folders from the NAS or dropbox.files_delete which would remove files or folders from dropbox.

If anything, if you're moving stuff around and using this app in full sync mode then eventually you're going to end up with multiple copies of the files you're moving around unless you do something about it (i.e. manually clean it up). 

This is the safest non-destructive way this app can work and I personally don't have any appetite to introduce any destructive data removal features or file / folder mirroring features. I'm sure it's possible to introduce this sort of feature but it's definitely a lot of work and I won't be taking it on.

**Comment by miketaster** [comment]
I figured as much.  So it works then!

The only problem I am having now is that I don't have write folder permissions to any of the child folders in the dropbox root on the NAS.  I can't write to the folders when using SMB or AFP or NFS.

**Comment by bebo-dot-dev** [comment]
Thanks for confirming, I'll package up a v2.2 release soon.

Sounds like you've got a NAS folder permissions problem there. The way I do it is like this (keep in mind this is linux mint -> NAS linux):

1. My NAS datasync folder is in /home/admin/datasync..basically in the admin users' home folder structure
2. I push files from machines on the LAN into this location on the NAS via an fstab mapped path which means that as far as a client machine is concerned, copying a file to the NAS is like copying a file to a local folder. NAS admin credentials are stored in the local key ring which I admit isn't bomb proof secure but it's good enough for me. Here's a couple of entries from my fstab to demonstrate what it looks like:
```
//192.168.0.2/home /media/nas_backup cifs credentials=/home/joe/.smbcredentials,uid=1000,gid=1000,rw,user,exec 0 0
//192.168.0.2/Public /media/nas_public cifs credentials=/home/joe/.smbcredentials,uid=1000,gid=1000,rw,user,exec 0 0
```
3. I run the whole thing from linux mint client to NAS using the excellent luckyBackup rsync based backup application which means I get scheduled backups from all my machines to the NAS and then later the offsite backup is maintained from NAS -> dropbox and NAS -> googledrive when these run on the NAS schedules

**Comment by miketaster** [comment]
Yeah.  My folder is in the same place.  I have no idea why the files downloaded and created from dropbox have no write permissions and have no idea where to fix it.

EDIT:  Found it.  It defaulted to root when it downloaded.

**Comment by bebo-dot-dev** [comment]
v2.2 is released: https://github.com/jjssoftware/asustor-dropbox/releases

If you applied the hotfix from the last issue you'll already have the fixes included in this release

I'm going to take a look at introducing a start_stop.sh script soon to better manage starting / stopping sync

This looks closed. Closing now.
