### ISSUE TITLE
File Synchronization

### ISSUE THREAD

**Issue by digobo** [jjssoftware/asustor-dropbox#4]
Hello,

The command seems to work well, but it has been more than 10 hours that I remain as a continuation and does not advance. The file only weighs 29GB, if I go to the log file it says nothing.

admin@Storage153:/volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages $ python /usr/local/AppCentral/community-dropbox-s
ync/bin/updown.py --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -y -u / /volume1/Backup_Nube/
Dropbox folder name: /
Local directory: /volume1/Backup_Nube/
Descend into Virtuales? [auto] YES
Keeping directory: Virtuales
Descend into BasesDatos? [auto] YES
Keeping directory: BasesDatos
Descend into Isbel? [auto] YES
Keeping directory: Isbel
Descend into Synapsis? [auto] YES
Keeping directory: Synapsis
Total elapsed time for list_folder: 0.907
Descending into Virtuales/Isbel ...
Upload and save xxxxxxx.ova? [auto] YES
Total elapsed time for upload 29490137600 bytes: 59258.838
uploaded as xxxxxxx.ova
Upload and save xxxxxxx.ova? [auto] YES

Can you help me?

**Comment by bebo-dot-dev** [comment]
29GB is not an insignificant volume of data to upload and upload could take some time depending on available bandwidth. Check the log file for progress.

**Comment by digobo** [comment]
Check the log and just give me this information:

13/11/2019 16:52:15 INFO Process started
15/11/2019 01:21:31 ERROR Caught a general exception at upload time; the process will continue. add, /volume1/Backup_Nube/Virtuales/Isbel/xxxx.ova, /Virtuales/Isbel/xxxx.ova HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload_session/append (Caused by SSLError(SSLError('The write operation timed out',),))

**Comment by bebo-dot-dev** [comment]
If this .ova file is what I think it is, a huge virtual appliance file, and it's taken about a day and a half for you to see anything in the log, you're basically doing it wrong.

It looks like you're attempting to do something that is practically impossible with the Dropbox API because it's taking so long to upload this one file, your network connection fell apart before the upload of that one file completed.

My advice is that you break your files up into manageable pieces or give up any hope of using Dropbox for this use case.
